micronaut.application.name=health-service

grpc.server.port=50051

#todo micronaut.casandra

# Cassandra (Legacy Prefix)
cassandra.default.enabled=true
cassandra.default.basic.contact-points[0]=localhost:9042
cassandra.default.basic.load-balancing-policy.local-datacenter=datacenter1
cassandra.default.basic.session-keyspace=doctor_service

# JWT
jwt.secret=${JWT_SECRET:super-secret-key-for-healthcare-system-jwt-2026}
jwt.access-expiry=86400000
jwt.refresh-expiry=604800000

# NATS
nats.default.addresses=nats://localhost:4223

# Logging
logger.levels.io.micronaut.context.env=TRACE
logger.levels.com.health=DEBUG

photon.base-url=https://photon.komoot.io
photon.search-limit=1

# Redis and Cache Configuration
redis.uri=redis://localhost:6380
micronaut.cache.redis.enabled=true
micronaut.cache.redis.caches.patients.expire-after-write=1h
micronaut.cache.redis.caches.doctors.expire-after-write=1h
micronaut.cache.redis.caches.doctor-locations.expire-after-write=10m
