micronaut.application.name=doctor-service

grpc.server.port=50051
grpc.channels.patient.address=localhost
grpc.channels.patient.port=50053
grpc.channels.patient.plaintext=true

cassandra.default.contact-points[0]=localhost:9042
cassandra.default.local-datacenter=datacenter1
cassandra.default.session-keyspace=doctor_service
cassandra.default.advanced.metadata.token-map.enabled=false
cassandra.default.basic.request.timeout=5s
cassandra.default.advanced.connection.connect-timeout=5s
cassandra.default.advanced.connection.init-query-timeout=5s
cassandra.default.advanced.reconnection-policy.base-delay=1s
cassandra.default.advanced.reconnection-policy.max-delay=10s

photon.base-url=https://photon.komoot.io
photon.search-limit=1

nats.enabled=true
nats.default.addresses[0]=nats://localhost:4222
nats.default.connection-timeout=5s
nats.default.max-reconnect=3
nats.default.reconnect-wait=1s

grpc.server.reflection.enabled=true