micronaut.application.name=doctor-service
micronaut.server.port=8080
micronaut.security.enabled=false

grpc.server.port=50051
grpc.channels.patient.address=localhost
grpc.channels.patient.port=50053
grpc.channels.patient.plaintext=true

cassandra.default.contact-points[0]=localhost:9042
cassandra.default.local-datacenter=datacenter1
cassandra.default.session-keyspace=doctor_service

photon.base-url=https://photon.komoot.io
photon.search-limit=1