package com.health.doctor.domain.model;

public enum AppointmentStatus {
    APPOINTMENT_STATUS_STATUS_UNSPECIFIED,
    APPOINTMENT_STATUS_PENDING,
    APPOINTMENT_STATUS_ACCEPTED,
    APPOINTMENT_STATUS_CANCELLED,
    APPOINTMENT_STATUS_POSTPONED,
    APPOINTMENT_STATUS_COMPLETED,
    APPOINTMENT_STATUS_NO_SHOW
}