micronaut.application.name=patient-service
micronaut.server.port=8081
micronaut.security.enabled=false

grpc.server.port=50053
grpc.channels.doctor.address=localhost
grpc.channels.doctor.port=50051
grpc.channels.doctor.plaintext=true

cassandra.default.contact-points[0]=localhost:9042
cassandra.default.local-datacenter=datacenter1
cassandra.default.session-keyspace=doctor_service

nats.default.addresses[0]=nats://localhost:4222

photon.base-url=https://photon.komoot.io
photon.search-limit=1